resources:
    App\Dto\ConsentDecisionRequest:
        shortName: 'consent-decision'
        operations:
            _api_consent_landing_page_optin:
                method: 'POST'
                uriTemplate: 'landing-page/{salesChannel}/optin'
                class: ApiPlatform\Metadata\Post
                status: 200
                input: App\Dto\ConsentDecisionRequest
                output: App\Dto\ConsentDecisionOutput
                processor: 'App\State\Processor\ConsentOptInProcessor'
            _api_consent_landing_page_optout:
                method: 'POST'
                uriTemplate: 'landing-page/{salesChannel}/optout'
                class: ApiPlatform\Metadata\Post
                status: 200
                input: App\Dto\ConsentDecisionRequest
                output: App\Dto\ConsentDecisionOutput
                processor: 'App\State\Processor\ConsentOptOutProcessor'
            _api_consent_modal_optin:
                method: 'POST'
                uriTemplate: 'modal/{salesChannel}/optin'
                class: ApiPlatform\Metadata\Post
                status: 200
                input: App\Dto\ConsentDecisionRequest
                output: App\Dto\ConsentDecisionOutput
                processor: 'App\State\Processor\ConsentModalOptInProcessor'
            _api_consent_modal_optout:
                method: 'POST'
                uriTemplate: 'modal/{salesChannel}/optout'
                class: ApiPlatform\Metadata\Post
                status: 200
                input: App\Dto\ConsentDecisionRequest
                output: App\Dto\ConsentDecisionOutput
                processor: 'App\State\Processor\ConsentModalOptOutProcessor'
