resources:
  App\Entity\Customer:
    attributes:
      pagination_items_per_page: 100

    operations:
      ApiPlatform\Metadata\GetCollection:
        filters:
          - customer.external_identifier_filter
          - customer.decision_date_filter

