resources:
    App\Entity\DemoEntity:
        shortName: demo-entities
        operations:
            ApiPlatform\Metadata\Get: ~
            ApiPlatform\Metadata\Post: ~
            ApiPlatform\Metadata\Patch: ~
            ApiPlatform\Metadata\Delete: ~
            ApiPlatform\Metadata\GetCollection: ~
        properties:
            id:
                identifier: true
