stages:
    - test

default:
    image: registry.gitlab.com/elvidep/docker-app:latest
    cache:
        paths:
            - vendor
    before_script:
        - source deps/dependencies.sh
        - setupSSH

tests:
    stage: test
    except:
        - /_notests$/
    variables:
        ENVIRONMENT: test
        MYSQL_ROOT_PASSWORD: root
        SSH_DISABLE_STRICT_KEY_CHECKING: 1
        APP_ENV: test
        DOCKER_AUTH_CONFIG: '{"auths":{"registry.gitlab.com":{"auth": "Z2l0bGFiK2RlcGxveS10b2tlbi05MDExOTp1TXZ2Q3h6N3phQUxNVFA4UXdkUg=="}}'
        ELVI_CONFIG_REPOSITORY_DIR: /builds/elviapp/elvi-account/deps/config-repository
    services:
        - name: mariadb:10.5.8
          alias: db
    script:
        - time composer install --prefer-dist --no-interaction --optimize-autoloader
        - rm -rf $ELVI_CONFIG_REPOSITORY_DIR
        - time git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/elvilibrary/config-repository.git $ELVI_CONFIG_REPOSITORY_DIR;
        - time bin/ecs check
        - time bin/phpunit
        - time bin/phpspec run
        - time bin/codecept build
        - time bin/codecept run --steps -vvv --fail-fast --debug
