App\Entity\DemoEntity:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: name
    properties:
        id:
            - Type:
                type: string
            - Length:
                min: 36
                max: 36
        name:
            - Type:
                type: string
            - NotBlank: ~
        isPublic:
            - Type:
                type: bool
