# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Dto/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter: ~

    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - 'ApiPlatform\Core\Bridge\Symfony\Validator\Exception\ValidationException'
                    - 'App\Exception\NoSuchUserException'
                    - 'App\Exception\NoVerifiedEmailException'
                    - 'App\Exception\TokenRefreshRequiredException'
                    - 'Auth0\SDK\Exception\InvalidTokenException'
                    - 'Symfony\Component\HttpKernel\Exception\BadRequestHttpException'
                    - 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException'
                    - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
                    - 'Symfony\Component\HttpKernel\Exception\UnsupportedMediaTypeHttpException'
                    - 'Symfony\Component\Security\Core\Exception\AccessDeniedException'
                    - 'Symfony\Component\Security\Core\Exception\AuthenticationCredentialsNotFoundException'
                    - 'Symfony\Component\Serializer\Exception\NotEncodableValueException'

    Sentry\Monolog\Handler:
        arguments:
            $hub: '@Sentry\State\HubInterface'
            $level: !php/const Monolog\Logger::ERROR
            $bubble: false
